const EErros = {
  CART_NOT_FOUND: 1,
  CART_GET_ERROR: 2,
  CART_PRODUCT_DELETE: 3,
  PRODUCT_NOT_FOUND: 4,
  UPDATE_PRODUCT_QUANTITY: 5,
  CART_ADD_PRODUCT: 6,
  CART_CREATE_ERROR: 7,
  CART_RENDER_ERROR: 8,
  PRODUCT_INSUFICIENT_STOCK: 9,
};

export default EErros;
